version: '3.3'

services:
  cb-db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - backend
    environment:
      MYSQL_ROOT_PASSWORD: somewordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress

  cb-wordpress:
    image: christiancb/cb-wordpress:latest
    networks:
      - backend
      - proxy
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
    deploy:
      labels:
        traefik.port: 80
        traefik.frontend.rule: "Host:cb-wordpress.192.168.20.217.nip.io"
        traefik.docker.network: 'proxy'
volumes:
  db_data: {}

networks:
  backend:
  proxy:
    external: true

